#!/bin/sh

set -e

function build_app {
  local platform=$1

  echo ">>> Building $platform app..."
  echo ""

  local archive=build/SpellingBeePlus_$platform.xcarchive

  xcodebuild \
    TEAM_ID=$TEAM_ID \
    -scheme "SpellingBeePlus ($platform)" \
    -destination "generic/platform=$platform" \
    -archivePath $archive \
    archive

  echo ">>> Archiving $platform app..."
  echo ""

  local export_options="build/exportOptions_$platform.plist"
  local export_path="build/export"
  local export_method=ad-hoc

  if [ "$platform" = "macOS" ]; then
    export_method=mac-application
  fi

  plist="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
  <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
  <plist version=\"1.0\">
    <dict>
      <key>method</key>
      <string>$export_method</string>

      <key>teamID</key>
      <string>$TEAM_ID</string>

      <key>iCloudContainerEnvironment</key>
      <string>Development</string>
    </dict>
  </plist>"

  echo "$plist" > $export_options

  xcodebuild \
    TEAM_ID=$TEAM_ID \
    -exportArchive \
    -archivePath $archive \
    -exportPath "$export_path" \
    -exportOptionsPlist "$export_options"

  if [ "$platform" = "iOS" ]; then
    mv "$export_path/SpellingBeePlus (iOS).ipa" "$export_path/SpellingBeePlus.ipa"
  else
    mv "$export_path/SpellingBeePlus (macOS).app" "$export_path/SpellingBeePlus.app"
    (cd $export_path && zip -r SpellingBeePlus.zip "SpellingBeePlus.app")
  fi
}

if [[ -z $DEPLOY_DEST ]]; then
  echo "DEPLOY_DEST must be defined"
  exit 1
fi

if [[ -z $TEAM_ID ]]; then
  echo "TEAM_ID must be defined"
  exit 1
fi

version=$(./version version)

grep -q $version CHANGELOG.md || (echo "Version $version not found in CHANGELOG.md" && exit 1)
git diff-index --quiet HEAD || (echo "Project has uncommitted changes" && exit 1)

echo ">>> Clearing previous builds..."
rm -rf ./build

build_app iOS
build_app macOS

echo ">>> Copying app to deploy host..."
echo ""

scp ./build/export/SpellingBeePlus.ipa $DEPLOY_DEST
scp ./build/export/SpellingBeePlus.zip $DEPLOY_DEST
scp CHANGELOG.md $DEPLOY_DEST

echo ">>> Tagging version $version..."
echo ""

git tag "v$version" HEAD

echo ""
echo ">>> Done."
