#!/bin/sh

set -e

function export_iOS_app {
  local archive=$1
  local export_path=$2
  local export_options="build/exportOptions_iOS.plist"
  local export_plist="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
  <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
  <plist version=\"1.0\">
    <dict>
      <key>method</key>
      <string>ad-hoc</string>

      <key>teamID</key>
      <string>$TEAM_ID</string>
    </dict>
  </plist>"
  echo "$export_plist" > $export_options

  xcodebuild \
    TEAM_ID=$TEAM_ID \
    -exportArchive \
    -archivePath $archive \
    -exportPath "$export_path" \
    -exportOptionsPlist "$export_options"
}

function export_macOS_app {
  local archive=$1
  local export_path=$2
  local export_options="build/exportOptions_macOS.plist"
  local export_plist="<?xml version=\"1.0\" encoding=\"UTF-8\"?>
  <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
  <plist version=\"1.0\">
    <dict>
      <key>destination</key>
      <string>upload</string>

      <key>method</key>
      <string>development</string>

      <key>signingStyle</key>
      <string>automatic</string>

      <key>teamID</key>
      <string>$TEAM_ID</string>
    </dict>
  </plist>"
  echo "$export_plist" > $export_options

  xcodebuild \
    TEAM_ID=$TEAM_ID \
    -exportArchive \
    -archivePath $archive \
    -exportPath "$export_path" \
    -exportOptionsPlist "$export_options"

  set +e

  until xcodebuild \
    TEAM_ID=$TEAM_ID \
    -exportNotarizedApp \
    -archivePath $archive \
    -exportPath "$export_path"
  do \
    echo "Notarization failed, retrying in 10 seconds"
    sleep 10
  done

  set -e

  (cd $export_path && zip -r SpellingBeePlus.zip "SpellingBeePlus.app")
}

function build_app {
  local platform=$1

  echo ">>> Building $platform app..."
  echo ""

  local archive=build/SpellingBeePlus_$platform.xcarchive

  xcodebuild \
    TEAM_ID=$TEAM_ID \
    -scheme "SpellingBeePlus ($platform)" \
    -destination "generic/platform=$platform" \
    -archivePath $archive \
    archive

  echo ">>> Archiving $platform app..."
  echo ""

  if [ $platform = "iOS" ]; then
    export_iOS_app $archive "build/export"
  else
    export_macOS_app $archive "build/export"
  fi
}

if [[ -z $DEPLOY_DEST ]]; then
  echo "DEPLOY_DEST must be defined"
  exit 1
fi

if [[ -z $TEAM_ID ]]; then
  echo "TEAM_ID must be defined"
  exit 1
fi

version=$(./version version)

grep -q $version CHANGELOG.md || (echo "Version $version not found in CHANGELOG.md" && exit 1)
git diff-index --quiet HEAD || (echo "Project has uncommitted changes" && exit 1)

echo ">>> Clearing previous builds..."
rm -rf ./build

build_app iOS
build_app macOS

echo ">>> Copying app to deploy host..."
echo ""

scp ./build/export/SpellingBeePlus.ipa $DEPLOY_DEST
scp ./build/export/SpellingBeePlus.zip $DEPLOY_DEST
scp CHANGELOG.md $DEPLOY_DEST

echo ">>> Tagging version $version..."
echo ""

git tag "v$version" HEAD

echo ""
echo ">>> Done."
