#!/bin/bash

if [[ $# -ne 2 ]]; then
  echo "Usage: deploy.sh <host> <dir>"
  exit 1
fi

host=$1
dir=$2

id=$(git rev-parse --short=7 HEAD)

echo ">>> Building..."
docker buildx build -t spellingbeeplus:latest -t spellingbeeplus:$id --platform linux/amd64 .

echo ">>> Uploading..."
docker save spellingbeeplus:latest spellingbeeplus:$id | ssh $host 'docker load'

echo ">>> Restarting service..."
ssh $host "cd $dir && docker compose up -d spellingbeeplus"

echo ">>> Done"
