// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrMsgKind } from "./ErrMsgKind";

export interface ErrMsg { kind: ErrMsgKind, message: string, }