// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageContent } from "./MessageContent";

export interface InternalMessage { to: string | null, from: string, content: MessageContent, }