// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connect } from "./Connect";
import type { ErrMsg } from "./ErrMsg";
import type { Joined } from "./Joined";
import type { Sync } from "./Sync";

export type MessageContent = { "connect": Connect } | { "setName": string } | { "setClientId": string } | { "sync": Sync } | { "noSync": string } | { "joined": Joined } | { "left": string } | { "error": ErrMsg };